Dt2
yalelibrary/yul-dc-iiif-imageserver pull request #16
Opened 2020-12-04 22:11 UTC by mlooney

2020-12-07 17:18 UTC, orangewolf requested changes, later dismissed

2020-12-07 17:18 UTC, orangewolf commented on ops/boot.sh
> +<<<<<<< HEAD
your diff is showing ;-)

2020-12-10 18:17 UTC, mlooney commented on ops/boot.sh
> +<<<<<<< HEAD
hah!

2020-12-10 22:59 UTC, fnibbit approved these changes

2021-01-13 16:48 UTC, merged